// Typed data access for the Earnings Intelligence dashboard.
//
// Two data paths, chosen by VITE_API_URL:
//   * unset/empty  -> snapshot mode: read the static JSON bundled with the
//     build (public/snapshot/*, generated by scripts/export_demo_data.py).
//     This is the demo's primary data source; no badge, no live requests.
//   * set          -> live mode: fetch the API with a hard 4s timeout; on
//     timeout or any non-2xx response fall back to the snapshot and flip the
//     fallback flag so the UI can show a "cached data" badge.

import type { BacktestResults, Filing, FilingText, Signal, Stats } from "../types";

const BASE_URL = (import.meta.env.VITE_API_URL ?? "").trim().replace(/\/+$/, "");
const LIVE_TIMEOUT_MS = 4000;

class ApiError extends Error {
  status: number;

  constructor(status: number, message: string) {
    super(message);
    this.name = "ApiError";
    this.status = status;
  }
}

// ---------------------------------------------------------------------------
// Snapshot fallback state (subscribed by the header badge via useFetch.ts).
// Only flips when a *configured* live API failed and the snapshot answered;
// pure snapshot mode is the normal data path, not a degraded one.
// ---------------------------------------------------------------------------

let fallbackActive = false;
const fallbackListeners = new Set<() => void>();

export function isSnapshotFallbackActive(): boolean {
  return fallbackActive;
}

export function subscribeSnapshotFallback(listener: () => void): () => void {
  fallbackListeners.add(listener);
  return () => {
    fallbackListeners.delete(listener);
  };
}

function markFallback(): void {
  if (fallbackActive) return;
  fallbackActive = true;
  for (const listener of fallbackListeners) listener();
}

// ---------------------------------------------------------------------------
// Snapshot loading + routing
// ---------------------------------------------------------------------------

type SnapshotFile = "stats" | "signals" | "filings" | "backtest" | "filing-texts";

const snapshotCache = new Map<SnapshotFile, Promise<unknown>>();

function loadSnapshotFile<T>(name: SnapshotFile): Promise<T> {
  let pending = snapshotCache.get(name);
  if (!pending) {
    pending = fetch(`/snapshot/${name}.json`).then((res) => {
      if (!res.ok) throw new ApiError(res.status, `Snapshot file ${name}.json is missing.`);
      return res.json() as Promise<unknown>;
    });
    snapshotCache.set(name, pending);
    // Don't cache a failed load; a retry should refetch.
    pending.catch(() => snapshotCache.delete(name));
  }
  return pending as Promise<T>;
}

// Serve an API path from the snapshot, applying the same filters the live
// endpoints apply server-side (ticker match, limit clamp, id lookup).
async function fromSnapshot<T>(path: string): Promise<T> {
  const url = new URL(path, "http://snapshot.local");
  const route = url.pathname;
  const params = url.searchParams;

  if (route === "/api/stats") {
    return loadSnapshotFile<T>("stats");
  }

  if (route === "/api/signals") {
    const all = await loadSnapshotFile<Signal[]>("signals");
    const ticker = params.get("ticker");
    const limit = Math.min(Math.max(Number(params.get("limit")) || 50, 1), 500);
    const filtered = ticker ? all.filter((s) => s.ticker === ticker) : all;
    return filtered.slice(0, limit) as T;
  }

  const signalMatch = route.match(/^\/api\/signals\/(\d+)$/);
  if (signalMatch) {
    const all = await loadSnapshotFile<Signal[]>("signals");
    const signal = all.find((s) => s.id === Number(signalMatch[1]));
    if (!signal) throw new ApiError(404, "Signal not found");
    return signal as T;
  }

  if (route === "/api/filings") {
    const all = await loadSnapshotFile<Filing[]>("filings");
    const ticker = params.get("ticker");
    const limit = Math.min(Math.max(Number(params.get("limit")) || 50, 1), 500);
    const filtered = ticker ? all.filter((f) => f.ticker === ticker) : all;
    return filtered.slice(0, limit) as T;
  }

  const textMatch = route.match(/^\/api\/filings\/(\d+)\/text$/);
  if (textMatch) {
    const texts = await loadSnapshotFile<Record<string, FilingText>>("filing-texts");
    const text = texts[textMatch[1]];
    if (!text) throw new ApiError(404, "Filing text not available");
    return text as T;
  }

  if (route === "/api/backtest/latest") {
    return loadSnapshotFile<T>("backtest");
  }

  throw new ApiError(404, `No snapshot data for ${route}`);
}

// ---------------------------------------------------------------------------
// Live API with timeout, falling back to the snapshot
// ---------------------------------------------------------------------------

async function fetchLive<T>(path: string): Promise<T> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), LIVE_TIMEOUT_MS);
  let res: Response;
  try {
    res = await fetch(`${BASE_URL}${path}`, { signal: controller.signal });
  } catch {
    throw new ApiError(0, `Cannot reach the API at ${BASE_URL} within ${LIVE_TIMEOUT_MS / 1000}s.`);
  } finally {
    clearTimeout(timer);
  }
  if (!res.ok) {
    let detail = res.statusText;
    try {
      const body = (await res.json()) as { detail?: string };
      if (body?.detail) detail = body.detail;
    } catch {
      // response had no JSON body; keep the status text
    }
    throw new ApiError(res.status, detail);
  }
  return (await res.json()) as T;
}

async function request<T>(path: string): Promise<T> {
  if (!BASE_URL) {
    // Snapshot mode: the bundled data IS the demo data.
    return fromSnapshot<T>(path);
  }

  try {
    return await fetchLive<T>(path);
  } catch (err) {
    const liveError =
      err instanceof ApiError ? err : new ApiError(0, "Unexpected API failure.");
    try {
      const data = await fromSnapshot<T>(path);
      markFallback();
      return data;
    } catch {
      // Snapshot couldn't answer either (e.g. unknown id): surface the live error.
      throw liveError;
    }
  }
}

function withQuery(path: string, params: Record<string, string | number | undefined>): string {
  const qs = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== "") qs.set(key, String(value));
  }
  const query = qs.toString();
  return query ? `${path}?${query}` : path;
}

export function getStats(): Promise<Stats> {
  return request<Stats>("/api/stats");
}

export function getSignals(ticker?: string, limit = 50): Promise<Signal[]> {
  return request<Signal[]>(withQuery("/api/signals", { ticker, limit }));
}

export function getSignal(id: number): Promise<Signal> {
  return request<Signal>(`/api/signals/${id}`);
}

export function getFilings(ticker?: string, limit = 50): Promise<Filing[]> {
  return request<Filing[]>(withQuery("/api/filings", { ticker, limit }));
}

export function getFilingText(id: number): Promise<FilingText> {
  return request<FilingText>(`/api/filings/${id}/text`);
}

// Returns null (not an error) when no backtest has been run yet (404), so the
// page can show its "not run yet" placeholder.
export async function getLatestBacktest(): Promise<BacktestResults | null> {
  try {
    return await request<BacktestResults>("/api/backtest/latest");
  } catch (err) {
    if (err instanceof ApiError && err.status === 404) return null;
    throw err;
  }
}

export { ApiError };
